var _ = require('lodash');

var origins = [
  {"id": 1, "name": "Rwanda", "description": "Since 2002, Rwanda has being changing the world perception about their coffee to be positioned as a specialty coffee producer. Since this moment, farmers have seen the value in producing specialty coffee, and the prices of the cherries have increased. Coffee represents an important exporting product for Rwandan economy, and from 2002 to 2006 the exportation of coffee grew a 30% per year. Long-term relationships were created with international buyers, guarantying the production and supply of coffee.The Rwanda government has developed a coffee program with five priority programs, which are the following:\nImproving the use of good farming practices and integrated pest management system through focused agronomist support\nProviding a voluntary turnaround support program for Coffee Washing Stations that have the potential to become profitable\nImproving sales and distribution mechanisms through capacity building of private exporters\nImplementing a census and GIS study of all coffee producing regions\nImplementing value addition activities including Toll Roasting in China, Toll Roasting in Middle East, and a partnership with M&S. "},
  {"id": 2, "name": "Colombia", "description": "Colombian coffee is often regarded as some of the highest quality coffee in the world. Colombia has traditionally grown arabica beans and its unique geography makes it perfectly suited for producing a delicious, high quality brew1. Colombia’s excellent growing conditions have paired with an aggressive marketing campaign by the National Federation of Coffee Growers (FNC), which has worked since the late 1950’s to bring Colombia’s coffee sector to the forefront of international attention. Colombia has traditionally been second in global coffee production only to Brazil2, but has been set back to third by Vietnam’s recent market entry and rapidly expanding production of robusta coffees. Over 500,000 farms, most of them small landholdings of 5 hectares or less3 are scattered across the zonas cafeteras, some of the most biologically diverse landscapes in the world. Colombia is bisected by the Andes Mountains which splits into three parallel cordilleras (mountain ranges) as they run south to north. Much of the nation’s coffee is grown in this area. The small nation, about three times the size of Montana4 contains two of South America’s five “biodiversity hotspots”5. The Tumbes-Choco hotspot occupies all of Colombia’s coast, while the Tropical Andes hotspot covers nearly all its mountain ranges. In fact, Conservation International calls the Colombian Andes the “richest and most diverse region on earth,” noting that the whole of the tropical Andes chain contains one sixth of the world’s plant species in only one percent of its land area5. "},
  {"id": 3, "name": "Kenya", "description": "Of all contemporary coffee origins, Kenya is doubtless the most universally admired. Coffee-growing came late to this mainly tea-drinking nation, introduced in 1900 by the British. When the Kenyans achieved independence they structured their coffee industry with what, in retrospect, seems admirable foresight. They maintained a technically sophisticated research establishment, made use of the most advanced techniques in fruit removal and drying, developed efficiently run cooperatives of small holders, and organized their export industry around an open auction.The auction system in particular may be the key to Kenya’s coffee success. The buyer who offers the highest price for a given lot of coffee at the weekly government-run auction gets that coffee. No insider deals can be cut. Samples of lots of coffee up for auction are distributed to licensed exporters, who evaluate them and distribute them to their customers for their evaluation. The exporters bid for the coffees based on their own evaluations and on the preferences of their customers.This simple, transparent system tends to reward higher quality with higher prices. Kenya coffee also has the advantage of consistently high growing altitudes and whatever imponderables of soil and climate contribute to the heady fruit and wine tones that embellish the best East Africa and Arabia coffees."},
  {"id": 4, "name": "Hawaii", "description": "The 'coffee belt' in Kona is approximately two miles wide from 700 feet (210 m) to 2,000 feet (610 m) elevation. Other districts on the island where coffee is grown include Kaʻū in the far south, Puna in the southeast, and Hāmākua in the northeast.[11]Although coffee can be harvested year-round in Hawaii, highest production begins in late summer and extends to early spring. In the 2008–2009 season, there were about 790 farms on the island of Hawaii, and 40 on other islands. Average yield was equivalent to 1400 pounds of parchment per acre. A total of about 7,800 acres (3,200 ha) are planted with coffee throughout the state. A little over half the acreage is outside the island of Hawaii, in particular on the island of Kauai, indicating that farms on other islands are larger in average size compared to those on Hawaii. Although total production increased from 2007 to about 8.6 million pounds, farm prices actually dropped, so the dollar value decreased by about 8%.[12] (Due to the relatively few coffee farms in Kauai, Maui and Honolulu counties their numbers are combined in USDA statistics to avoid disclosure of individual operations in those counties.) Several former sugarcane and pineapple plantations have changed to coffee production, such as Molokaʻi coffee."},
  {"id": 5, "name": "Indonesia Sumatra", "description": "Coffee from this western-most island in Indonesia is intriguing and complex, due to the large number of small-holder producers and the unique 'giling basah' (wet hulling) processing technique they use. At the green bean stage, coffee from this area has a distinctive bluish colour, which is attributed to processing method and lack of iron in the soil.Coffees from Sumatra are known for smooth, sweet body that is balanced and intense. Depending on the region, or blend of regions, the flavours of the land and processing can be very pronounced. Notes of cocoa, tobacco, smoke, earth and cedar wood can show well in the cup. Occasionally, Sumatran coffees can show greater acidity, which balances the body. This acidity takes on tropical fruit notes and sometimes an impression of grapefruit or lime."},
  {"id": 6, "name": "Guatemala", "description": "The highlands of Guatemala produce several of the world’s finest and most distinctive coffees. The mountain basin surrounding the austerely beautiful colonial city Guatemala Antigua produces the most distinguished of these highland coffees: Guatemala Antigua, a coffee that combines complex nuance (smoke, spice, flowers, occasionally chocolate) with acidity ranging from gently bright to austerely powerful. Fraijanes displays similar cup characteristics. Other Guatemala coffees, perhaps because they are more exposed to wet ocean weather than the mountain-protected Antigua basin, tend to display slightly softer, often less powerful, but equally complexly nuanced profiles. These softer Guatemalas include Cobán, admired for its fullish body and gentle, deep, rounded profile, Huehuetenango from the Caribbean-facing slopes of the central mountain range, and San Marcos coffees from the Pacific-facing slopes. Coffees from the basin surrounding Lake Atitlan in south central Guatemala typically offer the same complex nuance as Antiguas but are lighter in body and brighter in flavor.There are many excellent Guatemalan estates. To name just a small selection: in the Antigua Valley San Sebastián, La Tacita, San Rafael Urias, Pastores, and Las Nubes. In Huehuetenango Santa Cecilia, Huixoc, and El Coyegual. In the Coban region Yaxbatz, Los Alpes, and El Recreo. In San Marcos, Dos Marias."},
  {"id": 7, "name": "Ethiopia", "description": "Ethiopia is the world's seventh largest producer of coffee, and Africa's top producer, with 260,000 metric tonnes in 2006.[5] Half of the coffee is consumed by Ethiopians,[6] and the country leads the continent in domestic consumption.[7] The major markets for Ethiopian coffee are the EU (about half of exports), East Asia (about a quarter) and North America.[8] The total area used for coffee cultivation is estimated to be about 4,000 km2 (1,500 sq mi), the size is unknown due to the fragmented nature of the coffee farms.[9] The way of production has not changed much, with nearly all work, cultivating and drying, still done by hand.Ethiopian coffee beans that are grown in either the Harar, Sidamo, Yirgacheffe or Limu regions are kept apart and marketed under their regional name.These regional varieties are trademarked names with the rights owned by Ethiopia."},
  {"id": 8, "name": "Honduras", "description": "During the last 25 years, both the coffee producers and the Government of Honduras have made a quest to improve the quality of coffee from Honduras.  Laws have been passed giving fiscal incentives to coffee producers, highways have been built to access remote coffee growing regions, and the production has been technified by conducting soil analysis and determining the correct fertilizers to ensure a greater production and better quality. The result has been astonishingly effective in helping Honduras get a great name for its coffee. The vast majority of coffee from Honduras is Arabica, with several different strains grown that have been identified as the best for the climate conditions and geographic characteristics of Honduras, the most common being the Bourbon, Catuari, Caturra, Typica and Pacas strains."}
]

module.exports = {
  get: function(id) {
    return _.find(origins, function(origin){
      return origin.id == id;
    });
  },
  all: function() {
    return origins;
  }
}
